The code:

In [2]:
import numpy as np

In [3]:
N = np.array([1, 2, 3, 4, 5])
print(N)

[1 2 3 4 5]


In [4]:
a = np.array([[10.0, 20.0, 30.0], [10.0, 20.0, 30.0]])
print(a)

[[10. 20. 30.]
 [10. 20. 30.]]


Basics

In [5]:
#Get the number of dimensions of the array
print(a.ndim)
#Get the dimensions of the array
print(a.shape)
#Get the total number of elements in the array
print(a.size)
#Get the data type of the array
print(a.dtype)
#Get the size in bytes of each element of the array
print(a.itemsize)
#Get the total size in bytes of the array
print(a.nbytes)

2
(2, 3)
6
float64
8
48


Accessing

In [6]:
l = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(l, "\n")

#Get a specific element [row, column]
print(l[0, 5])
#Get a specific row
print(l[1, :])
#Get a specific column
print(l[:, 6])
#Get a specific part of a row
print(l[0, 1:6:2]) #from index 1 to index 6, step 2
#Get a specific part of a column   
print(l[0:2, 5]) #from index 0 to index 2, all rows, column 5
print("\n")

#3D array
m = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(m)
print(m[0, 1, 2])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]] 

6
[ 8  9 10 11 12 13 14]
[ 7 14]
[2 4 6]
[ 6 13]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


Changing 

In [7]:
#Changing an element
l[1, 5] = 20
print(l)
#Changing a row
l[0, :] = 15
print(l)
#Changing a column
l[:, 6] = 25
print(l)
#Changing a part of a row
l[0, 1:6] = 30
print(l)
#Changing a part of a column
l[0:2, 5] = 35
print(l)
#Changing all elements
l[:, :] = 0
print(l)
print("\n")

#3D array
m[1, 1, 1] = 20
print(m)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[15 15 15 15 15 15 15]
 [ 8  9 10 11 12 20 14]]
[[15 15 15 15 15 15 25]
 [ 8  9 10 11 12 20 25]]
[[15 30 30 30 30 30 25]
 [ 8  9 10 11 12 20 25]]
[[15 30 30 30 30 35 25]
 [ 8  9 10 11 12 35 25]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 20 12]]]


Initializing

In [8]:
#initializing arrays
#All zeros
z = np.zeros((3, 4))
print(z)
#All ones
o = np.ones((2, 3, 4), dtype='int32')
print(o)
#Any other number
f = np.full((2, 3), 99)
print(f)
#Any other number (full_like)
g = np.full_like(f, 4) #same shape as f, but filled with 4
print(g)
#Random decimal numbers 
r = np.random.rand(4, 2)
print(r)
#Random integer values
ri = np.random.randint(1, 100, size=(3, 3)) #from 1 to 100
print(ri)
#Identity matrix
i = np.identity(5)
print(i)
#Repeat an array
rep = np.array([1, 2, 3])
r = np.repeat(rep, 3) #repeat each element 3 times
print(r)
#Repeat a 2D array
rr = np.repeat(rep, 3, axis=0) #repeat each element 3 times along the rows
print(rr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[99 99 99]
 [99 99 99]]
[[4 4 4]
 [4 4 4]]
[[0.79509023 0.40747869]
 [0.5827217  0.67482741]
 [0.88815356 0.25527533]
 [0.73722574 0.05685179]]
[[ 4 34 28]
 [61 40 81]
 [39 77 27]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[1 1 1 2 2 2 3 3 3]
[1 1 1 2 2 2 3 3 3]


Practice

In [9]:
P = np.ones((5,5))
Z = np.zeros((3,3))
Z[1,1] = 9
P[1:4, 1:4] = Z #put Z in the middle of P
print(P)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
